name: Run CI checks

on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4' # The Go version to download (if necessary) and use.

      - name: Run tests
        run: |
          go test ./...
